# Generated by Django 3.0.7 on 2020-08-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='qty',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
    ]
