# Generated by Django 3.0.7 on 2020-12-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_project', '0002_part_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='assembly_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assembly Time'),
        ),
        migrations.AddField(
            model_name='part',
            name='detailing_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modeling Time'),
        ),
        migrations.AddField(
            model_name='part',
            name='modeling_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modeling Time'),
        ),
    ]
