# Generated by Django 3.0.7 on 2020-12-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_project', '0003_auto_20201221_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
